services:
  # Pihole ad blocking service
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    env_file:
      - path: ./.env
    environment:
      WEB_PORT: ${HOMEPAGE_VAR_PIHOLE_PORT}
    volumes:
      - ./dockerData/pihole/config:/etc/pihole
      - ./dockerData/pihole/dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  # Homepage for the lab
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - path: ./.env
    ports:
      - 80:3000
    volumes:
      - ./dockerData/homepage/:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # The disk for backup for DietPI
      - /mnt/backup:/backup
    restart: unless-stopped

  backrest:
    image: garethgeorge/backrest
    container_name: backrest
    env_file:
      - path: ./.env
    ports:
      - 9898:9898
    volumes:
      - ./dockerData/backrest/data:/data
      - ./dockerData/backrest/config:/config
      - ./dockerData/backrest/cache:/cache
      - /mnt/backup:/repo
      - ./dockerData:/toBackup
      - ./dockerData/backrest/restore:/restore
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - BACKREST_PORT=${HOMEPAGE_VAR_BACKREST_PORT}
    restart: unless-stopped
