---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Tools:
    - Pihole:
        href: https://pihole.{{HOMEPAGE_VAR_DOMAIN}}/admin
        icon: pi-hole
        container: pihole
        widget:
          type: pihole
          url: https://pihole.{{HOMEPAGE_VAR_DOMAIN}}
          key: {{HOMEPAGE_VAR_PIHOLE_API}}
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICEID}}
          key: {{HOMEPAGE_VAR_TAILSCALE_API}}
    - Traefik Proxy:
        icon: traefik
        href: http://proxy.{{HOMEPAGE_VAR_DOMAIN}}
        container: traefik

- Backup:
    - BackRest:
        icon: restic
        href: http://backrest.{{HOMEPAGE_VAR_DOMAIN}}
        container: backrest

- Monitoring:
    - Diun:
        icon: diun 
        container: diun

