---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Tools:
    - ADGuard Home:
        href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}/admin
        icon: adguard
        container: adguardhome
        widget:
          type: adguard
          url: https://dns.{{HOMEPAGE_VAR_DOMAIN}}
          username: {{HOMEPAGE_VAR_USER_ADGUARD}}
          password: "{{HOMEPAGE_VAR_PW_ADGUARD}}"
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICEID}}
          key: {{HOMEPAGE_VAR_TAILSCALE_API}}
    - Traefik Proxy:
        icon: traefik
        href: http://proxy.{{HOMEPAGE_VAR_DOMAIN}}
        container: traefik
        widget:
          type: traefik
          url: https://proxy.{{HOMEPAGE_VAR_DOMAIN}}
          username: admin
          password: "{{HOMEPAGE_VAR_PW_ADGUARD}}"

- Backup:
    - BackRest:
        icon: restic
        href: http://backrest.{{HOMEPAGE_VAR_DOMAIN}}
        container: backrest

- Monitoring:
    - Diun:
        icon: diun 
        container: diun
    - Gatus:
        icon: gatus
        container: gatus
        href: https://ping.{{HOMEPAGE_VAR_DOMAIN}}
        widget:
          type: gatus
          url: https://ping.{{HOMEPAGE_VAR_DOMAIN}}

