---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Tools:
    - ADGuard Home:
        href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}
        icon: adguard-home
        container: adguardhome
        widget:
          type: adguard
          url: https://dns.{{HOMEPAGE_VAR_DOMAIN}}
          username: {{HOMEPAGE_VAR_USER_ADGUARD}}
          password: "{{HOMEPAGE_VAR_PW_ADGUARD}}"
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICEID}}
          key: {{HOMEPAGE_VAR_TAILSCALE_API}}

- Tools:

  - Silverbullet:
      icon: silverbullet 
      href: https://notes.{{HOMEPAGE_VAR_DOMAIN}}
      container: silverbullet

- Monitoring:
    - Diun:
        icon: diun 
        container: diun

    - Beszel:
        icon: beszel
        href: https://stats.{{HOMEPAGE_VAR_DOMAIN}}
        container: beszel
        widget:
          type: beszel
          url: https://stats.{{HOMEPAGE_VAR_DOMAIN}}
          username: "{{HOMEPAGE_VAR_BESZEL_MAIL}}"
          password: "{{HOMEPAGE_VAR_BESZEL_PW}}"
          version: 2


