---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Tools:
    - PiHole:
        icon: pi-hole
        href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}/admin
        widget:
            type: pihole
            url: https://dns.{{HOMEPAGE_VAR_DOMAIN}}
            key: "{{HOMEPAGE_VAR_PIHOLE}}"
            version: 6
- Monitoring:
    - Diun:
        icon: diun
        container: diun

    - Beszel:
        icon: beszel
        href: https://stats.{{HOMEPAGE_VAR_DOMAIN}}
        container: beszel
        widget:
          type: beszel
          url: https://stats.{{HOMEPAGE_VAR_DOMAIN}}
          username: "{{HOMEPAGE_VAR_BESZEL_MAIL}}"
          password: "{{HOMEPAGE_VAR_BESZEL_PW}}"
          version: 2


- Entertainment:
    - Jellyfin:
        icon: jellyfin
        href: https://media.{{HOMEPAGE_VAR_DOMAIN}}
        container: jellyfin
        widget:
          type: jellyfin
          url: https://media.{{HOMEPAGE_VAR_DOMAIN}}
          key: "{{HOMEPAGE_VAR_JELLYFIN}}"
          enableUser: true # optional, defaults to false
    - Sonarr:
        icon: sonarr
        href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}
        container: sonarr
        widget:
          type: sonarr
          url: https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}
          key: "{{HOMEPAGE_VAR_SONARR}}"

    - Radarr:
        icon: radarr
        href: https://radarr.{{HOMEPAGE_VAR_DOMAIN}}
        cointainer: radarr
        widget:
          type: radarr
          url: https://radarr.{{HOMEPAGE_VAR_DOMAIN}}
          key: "{{HOMEPAGE_VAR_RADARR}}"

    - Prowlarr:
        icon: prowlarr
        href: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}
        cointainer: prowlarr
        widget:
          type: prowlarr
          url: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}
          key: "{{HOMEPAGE_VAR_PROWLARR}}"

    - QBittorrent:
        icon: qbittorrent
        href: https://torrent.{{HOMEPAGE_VAR_DOMAIN}}
        container: qbittorrent
        widget:
          type: qbittorrent
          url: https://torrent.{{HOMEPAGE_VAR_DOMAIN}}
          username: admin
          password: "{{HOMEPAGE_VAR_QBITTORENT}}"
          enableLeechProgress: false # optional, defaults to false
