---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homy
theme: dark
color: zinc

headerStyle: boxed
iconStyle: theme

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

layout:
  Network Tools:
    icon: mdi-web

  Entertainment:
    icon: mdi-music

  Monitoring:
    icon: mdi-chart-line

  Backup:
    icon: mdi-cloud-upload

  Tools:
    icon: mdi-tools
