---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Tools:
    - Pihole:
        href: http://{{HOMEPAGE_VAR_MACHINE_IP}}:{{HOMEPAGE_VAR_PIHOLE_PORT}}/admin
        icon: pi-hole
        container: pihole
        widget:
          type: pihole
          url: http://{{HOMEPAGE_VAR_MACHINE_IP}}:{{HOMEPAGE_VAR_PIHOLE_PORT}}
          key: {{HOMEPAGE_VAR_PIHOLE_API}}
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICEID}}
          key: {{HOMEPAGE_VAR_TAILSCALE_API}}

- Backup:
    - BackRest:
        icon: restic
        href: http://{{HOMEPAGE_VAR_MACHINE_IP}}:{{HOMEPAGE_VAR_BACKREST_PORT}}
        container: backrest

- Monitoring:
    - Diun:
        icon: diun 
        href: {{HOMEPAGE_VAR_DIUN_DISCORD_CHANNEL}}
        container: diun
