---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Tools:
    - Pihole:
        href: http://pihole.{{HOMEPAGE_VAR_MACHINE_IP}}/admin
        icon: pi-hole
        container: pihole
        widget:
          type: pihole
          url: https://pihole.{{HOMEPAGE_VAR_MACHINE_IP}}
          key: {{HOMEPAGE_VAR_PIHOLE_API}}
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICEID}}
          key: {{HOMEPAGE_VAR_TAILSCALE_API}}
    - Nginx Proxy Manager:
        icon: nginx
        href: https://proxy.{{HOMEPAGE_VAR_MACHINE_IP}}
        container: nginxproxymanager
        widget:
          type: npm
          url: https://proxy.{{HOMEPAGE_VAR_MACHINE_IP}}
          username: {{HOMEPAGE_VAR_NGINX_USER}}
          password: "{{HOMEPAGE_VAR_NGINX_PW}}"

- Backup:
    - BackRest:
        icon: restic
        href: http://backrest.{{HOMEPAGE_VAR_MACHINE_IP}}
        container: backrest

- Monitoring:
    - Diun:
        icon: diun 
        href: https://{{HOMEPAGE_VAR_DIUN_DISCORD_CHANNEL}}
        container: diun

